name = "ClimateGNSS"
uuid = "9be69d7f-1b74-4360-9256-abe98fd8b98c"
authors = ["Nathanael Wong <natgeo.wong@outlook.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
